### ISSUE TITLE
Can't escape usage of '%' in code blocks

### ISSUE THREAD

**Issue by kevinherron** [hendraanggrian/javapoet-ktx#3]
I don't see any way to escape usages of % in code blocks, e.g.:

```kotlin
appendln(
    """
    xmlDictionary.registerEnumCodec(
        new ${'$'}T.Codec().asXmlCodec(),
        String.format("//xs:element[@name='%s']", "$typeName"),
        $typeName.getTypeId().local(namespaceTable).orElseThrow(
            () -> new IllegalStateException("namespace not registered: " + NAMESPACE_URI))
    )
    """.trimIndent(),
    ClassName.get(enumTypePackageName, typeName)
)
```

will fail with:
```
Exception in thread "main" java.lang.IllegalArgumentException: index 2 for '$s' not in range (received 1 arguments)
	at com.squareup.javapoet.Util.checkArgument(Util.java:53)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:287)
	at com.squareup.javapoet.CodeBlock$Builder.addStatement(CodeBlock.java:402)
	at com.squareup.javapoet.MethodSpec$Builder.addStatement(MethodSpec.java:480)
	at com.hendraanggrian.javapoet.MethodSpecBuilder.appendln(MethodSpecs.kt:155)
```

because of my usage of `%s`.

**Comment by kevinherron** [comment]
For now I am using `\u0025` instead of a literal `%`, which your `formatWith` method does not find and replace.

**Comment by hendraanggrian** [comment]
Sorry for late reply, I just read this. In KotlinPoet, you use `%%` to escape template character `%`. I will implement this in coming days. Unless of course you have a better solution.

**Comment by hendraanggrian** [comment]
There has been some changes in `formatWith` to escape `%`. But I'm not entirely sure the [test] would suffice.

[test]: https://github.com/hendraanggrian/javapoet-ktx/blob/dff3080c7c582e6e6366031e42173481c8dab043/javapoet-ktx/tests/src/com/hendraanggrian/javapoet/CodeBlockBuilderTest.kt
